### ISSUE TITLE
Lua sort and group has to be refreshed to work

### ISSUE THREAD

**Issue by rptb1** [mpcjanssen/simpletask-android#1029]
I have `onSort` and `onGroup` functions defined for many saved filters. When I switch to a filter, the sorting often does not work until I go to the "SORT" menu and touch "Lua Script" (which is at the top) twice, forcing Simpletask to refresh.  I can get a similar effect by unchecking and checking "Use script".

Here are my functions:
```
function onGroup(t, f, e)
 if f.lists['urgent'] ~= nil then return "urgent"; end
 if f.due ~= nil then return os.date("%Y-%m-%d", f.due); end
 return "no due date";
end

function onSort(t, f, e)
 if f.lists['urgent'] ~= nil then return "0"; end
 if f.due ~= nil then return os.date("%Y-%m-%d", f.due); end
 return "9999";
end
```
The purpose of these is to give me a view grouped by due date, but with tasks marked with `@urgent` at the top.

Perhaps some optimization is cacheing results or avoiding calling the Lua when I switch filters?

Thanks.

(Simpletask Cloudless 10.3.3 from F-Droid.)

**Comment by mpcjanssen** [comment]
There was some caching added for the Lua scripts. I will check if this can cause issues.

**Comment by mpcjanssen** [comment]
@rptb1 can you check with a development build from https://www.mpcjanssen.nl/artifacts/ ? I have disabled caching so this issue should be fixed.

**Comment by rptb1** [comment]
I installed https://www.mpcjanssen.nl/artifacts/app-cloudless-debug.apk and that does seem to fix it (with only five minutes of testing though!)

By the way, there were several "Leak Canary" dumps.

**Comment by mpcjanssen** [comment]
So caching is the problem @smichel17 do you have time to look into this? If not I will remove caching for now. I will also look in the leak canary dumps.

**Comment by smichel17** [comment]
You can remove caching for now. My life has been simpler so I've been using paper todo lists recently; I'll look into this at whatever point I need Simpletask again :)

**Comment by silasdb** [comment]
The problem persists. Was this pushed to apps in F-Droid or Play Store? Is there something the user can make to enable/disable such "caching"? Maybe adding a checkbox to the Settings screen?

(Thanks for this great software!)

**Comment by mpcjanssen** [comment]
@silasdb there are (and will be) no new versions on google play (see #1102) instead the version at https://mpcjanssen.nl/artifacts/10.9.0/apk/cloudless/release/ has caching disabled.

**Comment by silasdb** [comment]
Thanks for the answer.  Unfortunatelly the problem persists for me.  I tried both the Cloudless version from F-Droid and the one you linked in this issue.

My sort script (onSort()) works but stops working as soon I edit a task.

I'm using Android 7.0.  Is there further configuration I need to make besides installing this specific version?

**Comment by silasdb** [comment]
I'm coming to apologize because it seems it was a problem with my configuration. After reinstalling and reviewing the settings, it works. Sorry for the confusion.

**Comment by silasdb** [comment]
Hi again. A minor issue: when I close the app and open it again it doesn't sort by Lua Script. Opening and closing Filter options, though, is enough to make sorting with Lua Script working.
