### ISSUE TITLE
Editing creates copy of item

### ISSUE THREAD

**Issue by jotwewe** [mpcjanssen/simpletask-android#307]
Steps to reproduce (doesn't happen everytime, but often):

- open simpletask from widget
- select item 
- edit
- close via 'ok' check mark

Often the item is saved as a new one (the one before the edit is still there, but also the edited one).

**Comment by mpcjanssen** [comment]
Selecting from the widget is not working as it should at the moment anyway. I will look into this when I have time.

**Comment by jotwewe** [comment]
It seems important to change the screen rotation between "edit" and "close via 'ok' check mark" to reproduce the bug. I usually browse the list in portrait orientation but edit in landscape.

**Comment by mpcjanssen** [comment]
@jotwewe is this still an issue in the latest version (7.0.9)

**Comment by jotwewe** [comment]
I'm on 7.0.12 now and it seems this issue is solved. However, although not
actually having tried to trigger it, I didn't notice it with the
version I previously had (6.0.9 AFAIK).

BTW, when marking an item as done from the list 7.0.12 is so slow
that I'd consider that a regression.

**Comment by mpcjanssen** [comment]
@jotwewe are you using autoarchive and are how big is your todo.txt (how many lines)

**Comment by jotwewe** [comment]
todo.txt has 189 lines, autoarchive is off.

**Comment by mpcjanssen** [comment]
If slowness is still an issue in the latest versins (which had some performance fixes) please log a specific issue for that.

**Comment by jotwewe** [comment]
I just experienced this bug again using 7.2.2.

And, by the way, slowness has improved, but it is still much slower than some previous version (6.x?). Using those versions, there was no lag at all..

**Comment by mpcjanssen** [comment]
@jotwewe the remaining slowness is a tradeoff between being fast and cleaning the tasklist at occasion and being a bit slower but keep the tasks.
If the duplication occurs again, could you send me a copy of the log (from Settings->Other->View Debug information?

**Comment by mpcjanssen** [comment]
Issue occurs when rotating the screen while editing.
